import type { Product } from "./types";

export const products: Product[] = [
  {
    id: "solara-rug",
    slug: "solara-hand-knotted-wool-rug",
    name: "Solara Hand-Knotted Wool Rug",
    origin: "India",
    originSlug: "india",
    collections: ["rugs", "best-sellers", "shop-all"],
    blurb: "Sun-faded medallion, knotted by hand in New Zealand wool.",
    description:
      "Solara takes a familiar medallion layout and eases it into a quieter geometry. Each rug is hand-knotted in Rajasthan from 100% New Zealand wool, then washed so the colour sits slightly uneven, as if it had already lived in a sunlit room. No two pieces match exactly.",
    details: [
      "Pile height about 8 mm",
      "Cotton warp",
      "Finished with a short fringe",
      "Made to order sizes are not offered",
    ],
    materials: "100% New Zealand wool pile on a cotton warp",
    madeIn: "India",
    care: "Vacuum without a beater bar. Blot spills at once. Professional clean only. Rotate every six months.",
    shipClass: "oversized",
    images: [
      "/images/prod-solara-rug.jpg",
      "/images/cat-rugs.jpg",
      "/images/banner-rugs.jpg",
      "/images/hero-living.jpg",
    ],
    variants: [
      { id: "solara-170", name: "170 x 240 cm", price: 88999 },
      { id: "solara-200", name: "200 x 300 cm", price: 124950 },
      { id: "solara-250", name: "250 x 350 cm", price: 179900 },
    ],
    bestseller: true,
    inStock: true,
    reviewScore: 4.8,
    reviewCount: 41,
  },
  {
    id: "atlas-kilim",
    slug: "atlas-flatweave-kilim",
    name: "Atlas Flatweave Kilim",
    origin: "Morocco",
    originSlug: "morocco",
    collections: ["rugs", "shop-all"],
    blurb: "A low, durable weave in terracotta, ivory, and charcoal.",
    description:
      "Woven on upright looms in the High Atlas foothills, this kilim is meant to be walked on daily. The stripe is broken by small stepped motifs so the floor does not read as a graphic poster. Reversible, with no pile to trap grit.",
    details: [
      "Flatweave, about 4 mm thick",
      "Finished with braided ends",
      "Reversible",
    ],
    materials: "Wool and cotton flatweave",
    madeIn: "Morocco",
    care: "Shake out outdoors. Spot clean with mild soap. Professional clean for full washes.",
    shipClass: "oversized",
    images: [
      "/images/prod-atlas-kilim.jpg",
      "/images/country-morocco.jpg",
      "/images/cat-rugs.jpg",
    ],
    variants: [
      { id: "atlas-140", name: "140 x 200 cm", price: 28999 },
      { id: "atlas-170", name: "170 x 240 cm", price: 48999 },
      { id: "atlas-200", name: "200 x 300 cm", price: 68950 },
    ],
    inStock: true,
    reviewScore: 4.6,
    reviewCount: 27,
  },
  {
    id: "mistfield-rug",
    slug: "mistfield-wool-area-rug",
    name: "Mistfield Wool Area Rug",
    origin: "Japan",
    originSlug: "japan",
    collections: ["rugs", "shop-all"],
    blurb: "A quiet grid in grey-green wool for rooms that need calm.",
    description:
      "Mistfield is a low-pile wool rug with an irregular grid, designed in our studio and woven in small lots. The colour sits between sage and stone so it layers under oak, plaster, and linen without competing.",
    details: [
      "Low pile, about 6 mm",
      "Cotton backing",
      "Use a non-slip underlay on smooth floors",
    ],
    materials: "Wool pile, cotton backing",
    madeIn: "Japan",
    care: "Vacuum on a low setting. Blot, do not rub. Professional clean as needed.",
    shipClass: "oversized",
    images: [
      "/images/prod-mistfield-rug.jpg",
      "/images/country-japan.jpg",
      "/images/cat-rugs.jpg",
    ],
    variants: [
      { id: "mist-170", name: "170 x 240 cm", price: 62950 },
      { id: "mist-200", name: "200 x 300 cm", price: 79900 },
      { id: "mist-250", name: "250 x 350 cm", price: 109999 },
    ],
    inStock: true,
    reviewScore: 4.7,
    reviewCount: 19,
  },
  {
    id: "tierra-jute",
    slug: "tierra-handwoven-jute-rug",
    name: "Tierra Handwoven Jute Rug",
    origin: "Mexico",
    originSlug: "mexico",
    collections: ["rugs", "archive-sale", "shop-all"],
    blurb: "A chunky jute lattice, last lengths from this season's weave.",
    description:
      "Tierra is a sturdy jute rug with a simple diamond lattice. It is from a closed dye lot, so once these sizes sell we will not remake this exact tone. Jute sheds in the first weeks. That is normal and eases with vacuuming.",
    details: [
      "Natural fibre, colour will mellow in sun",
      "Best in dry rooms, not bathrooms",
      "Final sale. Faulty goods are still covered under UK law",
    ],
    materials: "100% jute",
    madeIn: "Mexico",
    care: "Vacuum regularly. Keep dry. Avoid prolonged damp.",
    shipClass: "oversized",
    images: [
      "/images/prod-jute-rug.jpg",
      "/images/country-mexico.jpg",
      "/images/cat-rugs.jpg",
    ],
    variants: [
      { id: "tierra-140", name: "140 x 200 cm", price: 15999, compareAt: 22950 },
      { id: "tierra-170", name: "170 x 240 cm", price: 22950, compareAt: 32900 },
      { id: "tierra-200", name: "200 x 300 cm", price: 32999, compareAt: 44900 },
    ],
    archive: true,
    finalSale: true,
    inStock: true,
    reviewScore: 4.4,
    reviewCount: 33,
  },
  {
    id: "atlantic-linen",
    slug: "atlantic-stonewashed-linen-bundle",
    name: "Atlantic Stonewashed Linen Bundle",
    origin: "Portugal",
    originSlug: "portugal",
    collections: ["bedding", "best-sellers", "shop-all"],
    blurb: "Duvet cover, fitted sheet, and two pillowcases in flax linen.",
    description:
      "Woven in northern Portugal from European flax, then stonewashed so the bundle arrives soft rather than stiff. The colour is oat: warm without reading as yellow. Bundle includes one duvet cover, one deep fitted sheet, and two pillowcases.",
    details: [
      "Fitted sheet pocket 40 cm",
      "Button closure on the duvet cover",
      "Pillowcases envelope close",
      "Oeko-Tex Standard 100 fabrics",
    ],
    materials: "100% European flax linen, stonewashed",
    madeIn: "Portugal",
    care: "Machine wash 40°C with like colours. Line dry or tumble low. Iron on linen if you want a smoother face. Return unwashed in original packaging.",
    shipClass: "bedding",
    images: [
      "/images/prod-linen-set.jpg",
      "/images/cat-bedding.jpg",
      "/images/country-portugal.jpg",
      "/images/split-archive.jpg",
    ],
    variants: [
      { id: "atlantic-d", name: "Double", price: 18999 },
      { id: "atlantic-k", name: "King", price: 21950 },
      { id: "atlantic-sk", name: "Super King", price: 23999 },
    ],
    bestseller: true,
    inStock: true,
    reviewScore: 4.9,
    reviewCount: 86,
  },
  {
    id: "percale-sheets",
    slug: "organic-percale-sheet-set",
    name: "Organic Percale Sheet Set",
    origin: "Portugal",
    originSlug: "portugal",
    collections: ["bedding", "shop-all"],
    blurb: "Crisp long-staple organic cotton that cools overnight.",
    description:
      "A matte percale set for people who want hotel-calm sheets without a satin sheen. Woven from GOTS-certified organic long-staple cotton in Portugal. Set includes one flat sheet, one fitted sheet, and two pillowcases.",
    details: [
      "300 thread count percale",
      "Fitted sheet pocket 40 cm",
      "GOTS-certified cotton",
    ],
    materials: "100% organic long-staple cotton",
    madeIn: "Portugal",
    care: "Machine wash 40°C. Tumble low. Iron on cotton if desired. Return unwashed.",
    shipClass: "bedding",
    images: [
      "/images/prod-percale.jpg",
      "/images/cat-bedding.jpg",
      "/images/country-portugal.jpg",
    ],
    variants: [
      { id: "percale-d", name: "Double", price: 12950 },
      { id: "percale-k", name: "King", price: 14999 },
      { id: "percale-sk", name: "Super King", price: 16900 },
    ],
    inStock: true,
    reviewScore: 4.7,
    reviewCount: 52,
  },
  {
    id: "linen-duvet",
    slug: "heavyweight-linen-duvet-cover",
    name: "Heavyweight Linen Duvet Cover",
    origin: "Portugal",
    originSlug: "portugal",
    collections: ["bedding", "shop-all"],
    blurb: "A thicker flax cover in clay, sold on its own.",
    description:
      "For beds that already have sheets you like. This cover is a heavier linen than the Atlantic bundle, with a visible slub and a clay dye that will lighten slightly in the first few washes.",
    details: [
      "Button closure",
      "Interior ties at the corners",
      "Sold as a cover only, no insert",
    ],
    materials: "100% European flax linen",
    madeIn: "Portugal",
    care: "Wash 40°C. Line dry. Expect a little colour soften in the first washes. Return unwashed.",
    shipClass: "bedding",
    images: [
      "/images/prod-duvet.jpg",
      "/images/country-portugal.jpg",
      "/images/cat-bedding.jpg",
    ],
    variants: [
      { id: "duvet-d", name: "Double", price: 15900 },
      { id: "duvet-k", name: "King", price: 17950 },
      { id: "duvet-sk", name: "Super King", price: 19999 },
    ],
    inStock: true,
    reviewScore: 4.6,
    reviewCount: 24,
  },
  {
    id: "resort-towels",
    slug: "resort-cotton-towel-set",
    name: "Resort Cotton Towel Set",
    origin: "Portugal",
    originSlug: "portugal",
    collections: ["bedding", "shop-all"],
    blurb: "Four combed-cotton towels in sand, white, and sage.",
    description:
      "A set of two bath towels and two hand towels in long-staple combed cotton. The pile is dense without feeling stiff. Mix of sand, optical white, and pale sage so the set does not look like a hotel stack.",
    details: [
      "2 bath towels 70 x 140 cm",
      "2 hand towels 50 x 90 cm",
      "450 gsm terry",
    ],
    materials: "100% combed cotton",
    madeIn: "Portugal",
    care: "Wash 40°C. Avoid fabric softener, which reduces absorbency. Return unused and unwashed.",
    shipClass: "bedding",
    images: [
      "/images/prod-towels.jpg",
      "/images/cat-bedding.jpg",
      "/images/country-portugal.jpg",
    ],
    variants: [{ id: "towels-set", name: "Set of four", price: 4999 }],
    inStock: true,
    reviewScore: 4.5,
    reviewCount: 38,
  },
  {
    id: "waffle-robe",
    slug: "waffle-cotton-bath-robe",
    name: "Waffle Cotton Bath Robe",
    origin: "Portugal",
    originSlug: "portugal",
    collections: ["bedding", "shop-all"],
    blurb: "A unisex oat waffle robe that dries quickly.",
    description:
      "Lightweight enough for warm flats, with a waffle weave that dries faster than terry. Patch pockets, a self-belt, and a shawl collar. Cut generously.",
    details: ["Unisex fit", "Knee length", "Machine washable"],
    materials: "100% cotton waffle",
    madeIn: "Portugal",
    care: "Wash 40°C. Line dry. Return unused and unwashed.",
    shipClass: "bedding",
    images: ["/images/prod-robe.jpg", "/images/cat-bedding.jpg"],
    variants: [
      { id: "robe-sm", name: "S/M", price: 7950 },
      { id: "robe-lx", name: "L/XL", price: 8499 },
    ],
    inStock: true,
    reviewScore: 4.6,
    reviewCount: 21,
  },
  {
    id: "aegean-lumbar",
    slug: "aegean-lumbar-pillow",
    name: "Aegean Lumbar Pillow",
    origin: "Morocco",
    originSlug: "morocco",
    collections: ["pillows", "best-sellers", "shop-all"],
    blurb: "An oversized wool lumbar in dusty blue-grey.",
    description:
      "Handwoven wool with a faint stripe that reads as texture more than pattern. Sized for the back of a sofa. Feather-and-down insert included.",
    details: ["60 x 40 cm", "Hidden zip", "Insert included"],
    materials: "Wool cover, feather and down insert",
    madeIn: "Morocco",
    care: "Cover: professional clean. Insert: shake weekly. Spot clean the shell only.",
    shipClass: "standard",
    images: [
      "/images/prod-lumbar.jpg",
      "/images/cat-pillows.jpg",
      "/images/split-bestsellers.jpg",
    ],
    variants: [{ id: "aegean-one", name: "60 x 40 cm", price: 6499 }],
    bestseller: true,
    inStock: true,
    reviewScore: 4.8,
    reviewCount: 63,
  },
  {
    id: "sundara-cushion",
    slug: "sundara-block-print-cushion",
    name: "Sundara Block-Print Cushion",
    origin: "India",
    originSlug: "india",
    collections: ["pillows", "archive-sale", "shop-all"],
    blurb: "Hand-blocked cotton with a botanical repeat, last of the lot.",
    description:
      "Printed with carved wooden blocks in Jaipur. The botanical is our own drawing, not a licensed motif. Slight misregistration is part of the print. Feather insert included. Final sale.",
    details: ["50 x 50 cm", "Hidden zip", "Insert included", "Final sale"],
    materials: "Hand-blocked cotton, feather insert",
    madeIn: "India",
    care: "Cover: cold wash inside out, line dry. Do not tumble.",
    shipClass: "standard",
    images: [
      "/images/prod-blockprint.jpg",
      "/images/country-india.jpg",
      "/images/cat-pillows.jpg",
    ],
    variants: [
      { id: "sundara-one", name: "50 x 50 cm", price: 5450, compareAt: 7999 },
    ],
    archive: true,
    finalSale: true,
    inStock: true,
    reviewScore: 4.5,
    reviewCount: 18,
  },
  {
    id: "andes-pillow",
    slug: "andes-alpaca-pillow",
    name: "Andes Alpaca Pillow",
    origin: "Peru",
    originSlug: "peru",
    collections: ["pillows", "shop-all"],
    blurb: "A dense oatmeal alpaca square with a soft halo.",
    description:
      "Spun and woven in the Sacred Valley from alpaca fibre. The face is plush without looking like a novelty fur. Cotton back. Feather insert included.",
    details: ["45 x 45 cm", "Hidden zip", "Insert included"],
    materials: "Alpaca face, cotton back, feather insert",
    madeIn: "Peru",
    care: "Professional clean the cover. Keep away from direct heat.",
    shipClass: "standard",
    images: [
      "/images/prod-alpaca-pillow.jpg",
      "/images/country-peru.jpg",
      "/images/cat-pillows.jpg",
    ],
    variants: [{ id: "andes-one", name: "45 x 45 cm", price: 8900 }],
    inStock: true,
    reviewScore: 4.7,
    reviewCount: 29,
  },
  {
    id: "sling-chair",
    slug: "holm-oak-sling-chair",
    name: "Holm Oak Sling Chair",
    origin: "Portugal",
    originSlug: "portugal",
    collections: ["furniture", "shop-all"],
    blurb: "Solid oak frame with a vegetable-tanned leather sling.",
    description:
      "A low lounge chair built in a small joinery shop outside Porto. The frame is solid European oak with visible mortise work. The sling is vegetable-tanned leather that will darken where you sit. Arrives assembled.",
    details: [
      "Seat height 38 cm",
      "Overall 78 x 72 x 74 cm",
      "Leather will mark and patina",
      "Two-person delivery in the UK",
    ],
    materials: "Solid oak, vegetable-tanned leather",
    madeIn: "Portugal",
    care: "Dust the frame. Condition leather twice a year. Keep out of standing water.",
    shipClass: "oversized",
    images: [
      "/images/prod-sling-chair.jpg",
      "/images/cat-furniture.jpg",
      "/images/split-bestsellers.jpg",
    ],
    variants: [{ id: "holm-chair", name: "Oak / tan leather", price: 64500 }],
    inStock: true,
    reviewScore: 4.8,
    reviewCount: 14,
  },
  {
    id: "rattan-table",
    slug: "costa-rattan-side-table",
    name: "Costa Rattan Side Table",
    origin: "Mexico",
    originSlug: "mexico",
    collections: ["furniture", "archive-sale", "shop-all"],
    blurb: "Round rattan base, solid oak top, last of this finish.",
    description:
      "A light side table that still feels planted. The oak top is 2 cm thick. The rattan is bound by hand. This honey stain will not be repeated, which is why it sits in the Archive Sale. Ships in a carton, not as oversized furniture.",
    details: ["Diameter 50 cm", "Height 52 cm", "Final sale", "Ships as a parcel"],
    materials: "Rattan and solid oak",
    madeIn: "Mexico",
    care: "Wipe dry. Do not leave wet glasses sitting. Keep out of heavy rain if used indoors near doors.",
    shipClass: "standard",
    images: [
      "/images/prod-rattan-table.jpg",
      "/images/cat-furniture.jpg",
      "/images/country-mexico.jpg",
    ],
    variants: [
      { id: "costa-one", name: "50 cm diameter", price: 24950, compareAt: 32999 },
    ],
    archive: true,
    finalSale: true,
    inStock: true,
    reviewScore: 4.4,
    reviewCount: 22,
  },
  {
    id: "oak-bench",
    slug: "holm-oak-bench",
    name: "Holm Oak Bench",
    origin: "Portugal",
    originSlug: "portugal",
    collections: ["furniture", "shop-all"],
    blurb: "A solid oak bench for the end of a bed or a hallway.",
    description:
      "The same oak family as the sling chair. Slab seat, simple trestle legs, oil finish. Heavy enough that it does not skate on rugs. Two-person delivery in the UK.",
    details: ["Seat height 45 cm", "Depth 35 cm", "Arrives assembled"],
    materials: "Solid European oak, hardwax oil",
    madeIn: "Portugal",
    care: "Wipe with a damp cloth. Re-oil yearly if the grain looks dry.",
    shipClass: "oversized",
    images: [
      "/images/prod-oak-bench.jpg",
      "/images/cat-furniture.jpg",
      "/images/country-japan.jpg",
    ],
    variants: [
      { id: "bench-120", name: "120 cm", price: 42999 },
      { id: "bench-160", name: "160 cm", price: 52950 },
    ],
    inStock: true,
    reviewScore: 4.7,
    reviewCount: 11,
  },
  {
    id: "palm-basket",
    slug: "oaxaca-palm-market-basket",
    name: "Oaxaca Palm Market Basket",
    origin: "Mexico",
    originSlug: "mexico",
    collections: ["baskets", "shop-all"],
    blurb: "A natural palm basket with wrapped handles.",
    description:
      "Woven from palma in Oaxaca for carrying as much as for storage. The handles are wrapped so they do not cut into the hand. Colour varies with the harvest.",
    details: ["About 40 x 28 x 24 cm", "Handles sit above the rim"],
    materials: "Natural palm leaf",
    madeIn: "Mexico",
    care: "Keep dry. Reshape with steam if it is crushed in transit.",
    shipClass: "standard",
    images: [
      "/images/prod-palm-basket.jpg",
      "/images/cat-baskets.jpg",
      "/images/country-mexico.jpg",
    ],
    variants: [{ id: "palm-one", name: "One size", price: 3999 }],
    inStock: true,
    reviewScore: 4.6,
    reviewCount: 47,
  },
  {
    id: "seagrass-set",
    slug: "nested-seagrass-baskets",
    name: "Nested Seagrass Baskets",
    origin: "Morocco",
    originSlug: "morocco",
    collections: ["baskets", "shop-all"],
    blurb: "Three graduating seagrass bowls for blankets or kindling.",
    description:
      "A nested set of three open baskets. Tight coil, no lids. Useful beside a sofa or in a child's room. Sold only as a set.",
    details: ["Set of three", "Largest about 42 cm across"],
    materials: "Seagrass and grass coil",
    madeIn: "Morocco",
    care: "Dust. Keep dry.",
    shipClass: "standard",
    images: [
      "/images/prod-seagrass.jpg",
      "/images/cat-baskets.jpg",
      "/images/country-morocco.jpg",
    ],
    variants: [{ id: "seagrass-set", name: "Set of three", price: 5950 }],
    inStock: true,
    reviewScore: 4.5,
    reviewCount: 31,
  },
  {
    id: "paper-lantern",
    slug: "kyo-paper-pendant",
    name: "Kyo Paper Pendant",
    origin: "Japan",
    originSlug: "japan",
    collections: ["lighting", "shop-all"],
    blurb: "A spherical washi pendant with a warm, even glow.",
    description:
      "Handmade washi over a bamboo rib structure. The fitting is a standard E27 holder. Bulb not included. We recommend a warm LED of 2700K. Ceiling rose and 150 cm cord included.",
    details: [
      "E27 fitting",
      "Bulb not included",
      "Max 25W LED",
      "Professional installation recommended",
    ],
    materials: "Washi paper, bamboo ribs, steel fitting",
    madeIn: "Japan",
    care: "Dust with a soft brush. Do not wet the paper.",
    shipClass: "standard",
    images: [
      "/images/prod-lantern.jpg",
      "/images/country-japan.jpg",
      "/images/prod-ceramic-lamp.jpg",
    ],
    variants: [
      { id: "kyo-45", name: "45 cm", price: 11950 },
      { id: "kyo-60", name: "60 cm", price: 14999 },
    ],
    inStock: true,
    reviewScore: 4.8,
    reviewCount: 36,
  },
  {
    id: "ceramic-lamp",
    slug: "tejo-ceramic-table-lamp",
    name: "Tejo Ceramic Table Lamp",
    origin: "Portugal",
    originSlug: "portugal",
    collections: ["lighting", "shop-all"],
    blurb: "Speckled stoneware base with a linen drum shade.",
    description:
      "Thrown and glazed near the Tejo. The base is sand-speckled stoneware. The shade is a linen drum that throws light down onto a table as well as up. Inline switch on the cord. E14 fitting. Bulb not included.",
    details: ["Height 48 cm", "E14 fitting", "UK plug", "Bulb not included"],
    materials: "Stoneware, linen shade, fabric cord",
    madeIn: "Portugal",
    care: "Dust. Do not immerse the base.",
    shipClass: "standard",
    images: [
      "/images/prod-ceramic-lamp.jpg",
      "/images/country-portugal.jpg",
      "/images/split-bestsellers.jpg",
    ],
    variants: [{ id: "tejo-lamp", name: "One size", price: 17999 }],
    inStock: true,
    reviewScore: 4.7,
    reviewCount: 17,
  },
  {
    id: "alpaca-throw",
    slug: "cusco-alpaca-throw",
    name: "Cusco Alpaca Throw",
    origin: "Peru",
    originSlug: "peru",
    collections: ["throws", "best-sellers", "shop-all"],
    blurb: "A light alpaca blanket with a charcoal pinstripe.",
    description:
      "Woven in small workshops outside Cusco. Warm for its weight, which is why it works on a sofa in a heated flat. Fringed ends. 130 x 180 cm.",
    details: ["130 x 180 cm", "Fringed ends", "Natural fibre, slight colour shift lot to lot"],
    materials: "Alpaca and wool blend",
    madeIn: "Peru",
    care: "Professional clean. Store with cedar, not mothballs against the fibre.",
    shipClass: "standard",
    images: [
      "/images/prod-alpaca-throw.jpg",
      "/images/country-peru.jpg",
      "/images/prod-wool-throw.jpg",
    ],
    variants: [{ id: "cusco-throw", name: "130 x 180 cm", price: 14500 }],
    bestseller: true,
    inStock: true,
    reviewScore: 4.9,
    reviewCount: 58,
  },
  {
    id: "wool-throw",
    slug: "herringbone-wool-throw",
    name: "Herringbone Wool Throw",
    origin: "India",
    originSlug: "india",
    collections: ["throws", "shop-all"],
    blurb: "A denser wool throw in charcoal and flax herringbone.",
    description:
      "Tighter and heavier than the alpaca throw. Use it where you want the blanket to stay put. Woven in Himachal workshops we visit once a year.",
    details: ["130 x 170 cm", "Whipstitch edge"],
    materials: "100% wool",
    madeIn: "India",
    care: "Professional clean or cold hand wash. Dry flat.",
    shipClass: "standard",
    images: [
      "/images/prod-wool-throw.jpg",
      "/images/country-india.jpg",
      "/images/split-archive.jpg",
    ],
    variants: [{ id: "hb-throw", name: "130 x 170 cm", price: 9850 }],
    inStock: true,
    reviewScore: 4.6,
    reviewCount: 25,
  },
  {
    id: "dinner-set",
    slug: "tejo-stoneware-dinner-set",
    name: "Tejo Stoneware Dinner Set",
    origin: "Portugal",
    originSlug: "portugal",
    collections: ["tabletop", "shop-all"],
    blurb: "Speckled sand glaze. Four plates, four bowls, four mugs.",
    description:
      "A twelve-piece set from the same pottery as the table lamp. Microwave and dishwasher safe. The glaze pools a little at the rim, which we leave rather than grind back.",
    details: [
      "4 dinner plates 26 cm",
      "4 bowls 16 cm",
      "4 mugs 280 ml",
      "Dishwasher and microwave safe",
    ],
    materials: "Speckled stoneware, food-safe glaze",
    madeIn: "Portugal",
    care: "Dishwasher safe. Avoid sudden heat from freezer to oven.",
    shipClass: "standard",
    images: [
      "/images/prod-dinner-set.jpg",
      "/images/country-portugal.jpg",
      "/images/country-morocco.jpg",
    ],
    variants: [{ id: "tejo-set", name: "Set for four", price: 8999 }],
    inStock: true,
    reviewScore: 4.7,
    reviewCount: 44,
  },
  {
    id: "glassware",
    slug: "atlas-handblown-glassware",
    name: "Atlas Handblown Glassware",
    origin: "Morocco",
    originSlug: "morocco",
    collections: ["tabletop", "shop-all"],
    blurb: "Six mixed glasses in smoky amber and clear.",
    description:
      "Blown in small batches. Walls are slightly uneven, which is the point. Set of six: three amber, three clear. About 280 ml each. Not for the freezer.",
    details: ["Set of six", "About 280 ml", "Hand wash recommended"],
    materials: "Handblown soda-lime glass",
    madeIn: "Morocco",
    care: "Hand wash. Do not thermal shock.",
    shipClass: "standard",
    images: [
      "/images/prod-glassware.jpg",
      "/images/country-morocco.jpg",
      "/images/split-bestsellers.jpg",
    ],
    variants: [{ id: "atlas-six", name: "Set of six", price: 7450 }],
    inStock: true,
    reviewScore: 4.5,
    reviewCount: 20,
  },
  {
    id: "serving-board",
    slug: "mesa-oak-serving-board",
    name: "Mesa Oak Serving Board",
    origin: "Mexico",
    originSlug: "mexico",
    collections: ["tabletop", "shop-all"],
    blurb: "A thick carved oak board for bread or cheese.",
    description:
      "Carved from a single oak blank, then oiled. One shallow juice groove. Not a chopping block for heavy butchery; use it to serve.",
    details: ["About 45 x 22 cm", "Food-safe oil finish"],
    materials: "Oak",
    madeIn: "Mexico",
    care: "Hand wash, dry at once, oil monthly.",
    shipClass: "standard",
    images: [
      "/images/prod-board.jpg",
      "/images/country-mexico.jpg",
      "/images/cat-furniture.jpg",
    ],
    variants: [{ id: "mesa-board", name: "One size", price: 4200 }],
    inStock: true,
    reviewScore: 4.6,
    reviewCount: 16,
  },
];

export function getProduct(slug: string) {
  return products.find((item) => item.slug === slug);
}

export function productsIn(collection: string) {
  if (collection === "shop-all") return products;
  return products.filter(
    (item) =>
      item.collections.includes(collection) || item.originSlug === collection,
  );
}

export function relatedProducts(product: Product, limit = 4) {
  return products
    .filter((item) => item.id !== product.id)
    .filter(
      (item) =>
        item.originSlug === product.originSlug ||
        item.collections.some((c) => product.collections.includes(c) && c !== "shop-all"),
    )
    .slice(0, limit);
}

export function searchProducts(query: string) {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  return products.filter((item) =>
    [item.name, item.origin, item.blurb, item.materials, item.madeIn]
      .join(" ")
      .toLowerCase()
      .includes(q),
  );
}
